# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#858187,fg+:#fcfcfa,bg:-1,bg+:-1,hl:#fc9867,hl+:#ff6188:bold,gutter:-1,border:#2d2a2e,separator:#2d2a2e,scrollbar:#2d2a2e,preview-fg:#fcfcfa,preview-bg:-1,preview-border:#2d2a2e,preview-scrollbar:#2d2a2e,prompt:#ffd866,pointer:#ff6188,marker:#fc9867,spinner:#19181a,info:#858187,header:#858187,query:#78dce8,disabled:#858187,label:#858187'
export THEME_MOOR_HINT='ESC[38;2;133;129;135m'
export THEME_RGB_TEXT_MUTED='133 129 135'
export THEME_RGB_ACCENT_TERTIARY='252 152 103'
export THEME_RGB_ACCENT_AMBER='25 24 26'
export THEME_RGB_ACCENT_PRIMARY='255 97 136'
