# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#403e41,fg+:#fcfcfa,bg:-1,bg+:-1,hl:#fc9867,hl+:#ff6188:bold,gutter:-1,border:#2d2a2e,separator:#2d2a2e,scrollbar:#2d2a2e,preview-fg:#fcfcfa,preview-bg:-1,preview-border:#2d2a2e,preview-scrollbar:#2d2a2e,prompt:#ffd866,pointer:#ff6188,marker:#fc9867,spinner:#221f22,info:#403e41,header:#403e41,query:#78dce8,disabled:#403e41,label:#403e41'
export THEME_MOOR_HINT='ESC[38;2;64;62;65m'
export THEME_RGB_TEXT_MUTED='64 62 65'
export THEME_RGB_ACCENT_TERTIARY='252 152 103'
export THEME_RGB_ACCENT_AMBER='34 31 34'
export THEME_RGB_ACCENT_PRIMARY='255 97 136'
