#!/usr/bin/env bash

# Active palette colors (generated by `theme switch`).
source "$HOME/.config/theme/active/sketchybar/colors.sh"

# Batch-color ALL workspace indicators in ONE sketchybar call, driven by $FOCUSED_WORKSPACE
# (passed with the aerospace_workspace_change trigger; no IPC). Replaces 7 per-item aerospace.sh
# forks. Falls back to one aerospace query if the env var is absent (startup --update).
ACTIVE=$THEME_BAR_TEXT
INACTIVE=$THEME_BAR_TEXT_INACTIVE
WS="${FOCUSED_WORKSPACE:-$(aerospace list-workspaces --focused --format '%{workspace}' 2>/dev/null)}"

CMD=(sketchybar)
for sid in "1^" "1*" "2*" "3*" "2^"; do
  if [ "$sid" = "$WS" ]; then c=$ACTIVE; else c=$INACTIVE; fi
  CMD+=(--set "space.$sid" icon.color="$c")
done
"${CMD[@]}"
