# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#916c48,fg+:#ffffff,bg:-1,bg+:-1,hl:#d74545,hl+:#ffaf00:bold,gutter:-1,border:#1c1510,separator:#1c1510,scrollbar:#1c1510,preview-fg:#ffffff,preview-bg:-1,preview-border:#1c1510,preview-scrollbar:#1c1510,prompt:#0000df,pointer:#ffaf00,marker:#d74545,spinner:#902020,info:#916c48,header:#916c48,query:#e6a75a,disabled:#916c48,label:#916c48'
export THEME_MOOR_HINT='ESC[38;2;145;108;72m'
export THEME_RGB_TEXT_MUTED='145 108 72'
export THEME_RGB_ACCENT_TERTIARY='215 69 69'
export THEME_RGB_ACCENT_AMBER='144 32 32'
export THEME_RGB_ACCENT_PRIMARY='255 175 0'
