import assert from "node:assert/strict";
import { existsSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { acknowledgeExecutionPacket, buildTmuxDetachedPaneArgs, buildTmuxNewWindowArgs, cancelUnclaimedExecutionPacket, consumeExecutionPacket, deleteExecutionPacket, renderPlanMarkdown, waitForExecutionAcknowledgement, writeExecutionPacket } from "./execution-handoff.ts";
import { applyPlanUpdate, createPlanState } from "./plan-state.ts";
const model = { provider: "test", model: "model", thinkingLevel: "medium" as const };
const brief = { summary: "summary", findings: ["finding"], decisions: ["decision"], relevantFiles: [{ path: "index.ts", note: "flow" }], constraints: ["safe"] };
test("plan handoff is claimed once, acknowledges readiness, and cleans lifecycle files", async () => { const dir = mkdtempSync(join(tmpdir(), "plan-mode-handoff-")); try { const plan = applyPlanUpdate(createPlanState(), { goal: "Ship", steps: ["Inspect"], executionBrief: brief }); const path = writeExecutionPacket(dir, { version: 2, plan: { ...plan, workstreams: [{ id: "stale" }], parallelRun: { id: "stale" } }, source: { sessionId: "id", cwd: "/tmp/project", tmuxSession: "work" }, model }); const consumed = consumeExecutionPacket(dir, path); assert.equal(consumed?.source.tmuxSession, "work"); assert.equal(consumeExecutionPacket(dir, path), undefined); assert.equal("workstreams" in (consumed?.plan ?? {}), false); assert.equal("parallelRun" in (consumed?.plan ?? {}), false); assert.equal(await waitForExecutionAcknowledgement(dir, path, 20), "claimed"); assert.equal(acknowledgeExecutionPacket(dir, path), true); assert.equal(await waitForExecutionAcknowledgement(dir, path, 100), "ready"); deleteExecutionPacket(dir, path); assert.equal(existsSync(path), false); assert.equal(existsSync(`${path}.claim`), false); assert.equal(existsSync(`${path}.ack`), false); } finally { rmSync(dir, { recursive: true, force: true }); } });

test("an unclaimed handoff is atomically fenced before ownership returns to the source", async () => { const dir = mkdtempSync(join(tmpdir(), "plan-mode-handoff-")); try { const plan = applyPlanUpdate(createPlanState(), { goal: "Ship", steps: ["Inspect"], executionBrief: brief }); const path = writeExecutionPacket(dir, { version: 2, plan, source: { sessionId: "id", cwd: "/tmp/project", tmuxSession: "work" }, model }); assert.equal(await waitForExecutionAcknowledgement(dir, path, 20), "unclaimed"); assert.equal(cancelUnclaimedExecutionPacket(dir, path), true); assert.equal(existsSync(path), false); assert.equal(consumeExecutionPacket(dir, path), undefined); } finally { rmSync(dir, { recursive: true, force: true }); } });

test("a completed claim prevents the source from reclaiming execution", () => { const dir = mkdtempSync(join(tmpdir(), "plan-mode-handoff-")); try { const plan = applyPlanUpdate(createPlanState(), { goal: "Ship", steps: ["Inspect"], executionBrief: brief }); const path = writeExecutionPacket(dir, { version: 2, plan, source: { sessionId: "id", cwd: "/tmp/project", tmuxSession: "work" }, model }); assert.ok(consumeExecutionPacket(dir, path)); assert.equal(cancelUnclaimedExecutionPacket(dir, path), false); deleteExecutionPacket(dir, path); } finally { rmSync(dir, { recursive: true, force: true }); } });

test("clipboard markdown includes the complete execution brief", () => { const plan = applyPlanUpdate(createPlanState(), { goal: "Ship", steps: ["Inspect"], executionBrief: brief }); const markdown = renderPlanMarkdown(plan); for (const text of ["summary", "finding", "decision", "`index.ts` — flow", "safe"]) assert.match(markdown, new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))); });
test("detached tmux argv preserves cwd, source focus, direction, and no plan text", () => { const target = { session: "work", window: "@4", pane: "%9" }; const path = "/tmp/handoff.json"; for (const args of [buildTmuxNewWindowArgs(target, "/tmp/project", path, model), buildTmuxDetachedPaneArgs(target, "/tmp/project", path, model), buildTmuxDetachedPaneArgs(target, "/tmp/project", path, model, "right")]) { assert.ok(args.includes(`PI_PLAN_HANDOFF=${path}`)); assert.match(args.at(-1) ?? "", /^pi --provider/); assert.match(args.at(-1) ?? "", /exec "\$\{SHELL:-\/bin\/zsh\}" -l$/); assert.doesNotMatch(args.join(" "), /summary|finding|# Plan/); } assert.ok(buildTmuxDetachedPaneArgs(target, "/tmp/project", path, model).includes("-v")); assert.ok(buildTmuxDetachedPaneArgs(target, "/tmp/project", path, model, "right").includes("-h")); });
