import assert from "node:assert/strict";
import test from "node:test";
import { applyPlanUpdate, canClosePlan, createPlanState, enterRestrictedMode, leaveRestrictedMode, migratePlanState, pendingSteps, validateWorkstreams } from "./plan-state.ts";

const brief = { summary: "Implement safely", findings: ["Existing handoff is one-way"], decisions: ["Use acknowledgement"], relevantFiles: [{ path: "index.ts", note: "execution flow" }], constraints: ["Do not persist transcripts"] };
const update = (state = createPlanState()) => applyPlanUpdate(state, { goal: "Ship the change", steps: ["Inspect current behavior", "Implement the change"], executionBrief: brief });

test("plan updates preserve stable IDs and completed steps with unchanged text", () => { const initial = update(); initial.steps[0]!.completed = true; const id = initial.steps[0]!.id; const revised = applyPlanUpdate(initial, { goal: "Ship the narrowed change", steps: ["Inspect current behavior", "Implement the narrowed change", "Verify the result"], executionBrief: brief }); assert.equal(revised.steps[0]!.id, id); assert.equal(revised.steps[0]!.completed, true); assert.deepEqual(pendingSteps(revised).map((step) => step.text), ["Implement the narrowed change", "Verify the result"]); });
test("a plan closes only after every step is terminal", () => { const state = update({ ...createPlanState(), phase: "executing" }); state.steps[0]!.completed = true; assert.equal(canClosePlan(state), false); state.steps[1]!.skipped = true; assert.equal(canClosePlan(state), true); });
test("v3 access mode cycle preserves paused work and exact baseline", () => { const baseline = ["read", "bash", "custom_tool"]; let state = createPlanState(); state = enterRestrictedMode(state, "plan", baseline); assert.equal(state.phase, "drafting"); state = update(state); state = enterRestrictedMode(state, "read-only", ["read"]); const left = leaveRestrictedMode(state); assert.deepEqual(left.restoreTools, baseline); const reopened = enterRestrictedMode(left.state, "plan", baseline); assert.equal(reopened.phase, "ready"); });
test("v2-v4 plans migrate to v5 with IDs and stale workstreams cleared", () => { const v2 = migratePlanState({ version: 2, phase: "planning", toolsBeforePlan: ["read"] }); assert.equal(v2?.version, 5); assert.equal(v2?.accessMode, "plan"); assert.deepEqual(v2?.executionBrief, { summary: "", findings: [], decisions: [], relevantFiles: [], constraints: [] }); const v4 = migratePlanState({ version: 4, accessMode: "none", phase: "ready", goal: "Old", steps: [{ step: 1, text: "Old step", completed: false, skipped: false }], criteria: [], followUps: [], executionBrief: brief, workstreams: [{ id: "stale" }], widgetCollapsed: true, awaitingReview: false, resumeAfterRevision: false, completionRequested: false }); assert.equal(v4?.version, 5); assert.equal(v4?.steps[0]?.id, "legacy-1"); assert.equal(v4?.workstreams, undefined); });
test("workstreams partition steps and reject duplicate assignments or overlapping paths", () => { const state = applyPlanUpdate(createPlanState(), { goal: "Ship", steps: ["One", "Two", "Three"], executionBrief: brief }); const streams = validateWorkstreams([{ id: "runtime", title: "Runtime", objective: "Build runtime", steps: [1, 3], ownedPaths: ["extensions/tmux"] }, { id: "plan", title: "Plan", objective: "Build plan", steps: [2], ownedPaths: ["extensions/plan-mode"] }], state.steps); assert.deepEqual(streams.map((stream) => stream.stepIds.length), [2, 1]); assert.throws(() => validateWorkstreams([{ id: "one", title: "One", objective: "One", steps: [1, 2], ownedPaths: ["a"] }, { id: "two", title: "Two", objective: "Two", steps: [2, 3], ownedPaths: ["a/b"] }], state.steps), /unique valid plan step numbers|must not overlap/); });
test("manual plan edits clear stale workstreams unless they are rebuilt", () => { const state = applyPlanUpdate(createPlanState(), { goal: "Ship", steps: ["One", "Two"], executionBrief: brief, workstreams: [{ id: "one", title: "One", objective: "One", steps: [1], ownedPaths: ["a"] }, { id: "two", title: "Two", objective: "Two", steps: [2], ownedPaths: ["b"] }] }); assert.equal(state.workstreams?.length, 2); assert.equal(applyPlanUpdate(state, { goal: state.goal, steps: ["One", "Changed"], executionBrief: brief }).workstreams, undefined); });
