import assert from "node:assert/strict";
import test from "node:test";
import { applyPlanUpdate, canClosePlan, createPlanState, enterRestrictedMode, leaveRestrictedMode, materializePlan, migratePlanState, pendingSteps, updatePlanStep } from "./plan-state.ts";

const brief = { summary: "Implement safely", findings: ["Existing handoff is one-way"], decisions: ["Use acknowledgement"], relevantFiles: [{ path: "index.ts", note: "execution flow" }], constraints: ["Do not persist transcripts"] };
const update = (state = createPlanState()) => applyPlanUpdate(state, { goal: "Ship the change", steps: ["Inspect current behavior", "Implement the change"], executionBrief: brief });

test("plan updates preserve stable IDs and completed steps with unchanged text", () => { const initial = updatePlanStep(update(), 1, "complete"); const id = initial.steps[0]!.id; const revised = applyPlanUpdate(initial, { goal: "Ship the narrowed change", steps: ["Inspect current behavior", "Implement the narrowed change", "Verify the result"], executionBrief: brief }); assert.equal(revised.steps[0]!.id, id); assert.equal(revised.steps[0]!.completed, true); assert.deepEqual(pendingSteps(revised).map((step) => step.text), ["Implement the narrowed change", "Verify the result"]); });
test("duplicate step labels retain distinct identities and status in occurrence order", () => { const initial = applyPlanUpdate(createPlanState(), { goal: "Ship", steps: ["Verify", "Verify"], executionBrief: brief }); const completed = updatePlanStep(initial, 2, "complete"); const revised = applyPlanUpdate(completed, { goal: "Ship", steps: ["Verify", "Verify"], executionBrief: brief }); assert.notEqual(revised.steps[0]!.id, revised.steps[1]!.id); assert.equal(revised.steps[0]!.completed, false); assert.equal(revised.steps[1]!.completed, true); assert.equal(initial.steps[1]!.completed, false); });
test("materializing a plan assigns one stable sequential identity", () => { const first = materializePlan(update(), "2026-01-01T00:00:00.000Z"); const again = materializePlan(first, "2026-01-02T00:00:00.000Z"); assert.ok(first.planId); assert.equal(again.planId, first.planId); assert.equal(again.createdAt, "2026-01-01T00:00:00.000Z"); });
test("a plan closes only after every step is terminal", () => { const state = update({ ...createPlanState(), phase: "executing" }); state.steps[0]!.completed = true; assert.equal(canClosePlan(state), false); state.steps[1]!.skipped = true; assert.equal(canClosePlan(state), true); });
test("restricted-mode cycle preserves paused work and exact baseline", () => { const baseline = ["read", "bash", "custom_tool"]; let state = createPlanState(); state = enterRestrictedMode(state, "plan", baseline); assert.equal(state.phase, "drafting"); state = update(state); state = enterRestrictedMode(state, "read-only", ["read"]); const left = leaveRestrictedMode(state); assert.deepEqual(left.restoreTools, baseline); const reopened = enterRestrictedMode(left.state, "plan", baseline); assert.equal(reopened.phase, "ready"); });
test("v2-v5 plans migrate to v6 with IDs and obsolete parallel state removed", () => { const v2 = migratePlanState({ version: 2, phase: "planning", toolsBeforePlan: ["read"] }); assert.equal(v2?.version, 6); assert.equal(v2?.accessMode, "plan"); assert.deepEqual(v2?.executionBrief, { summary: "", findings: [], decisions: [], relevantFiles: [], constraints: [] }); const v5 = migratePlanState({ version: 5, accessMode: "none", phase: "ready", goal: "Old", steps: [{ step: 1, text: "Old step", completed: false, skipped: false }], criteria: [], followUps: [], executionBrief: brief, workstreams: [{ id: "stale" }], parallelRun: { id: "stale" }, widgetCollapsed: true, awaitingReview: false, resumeAfterRevision: false, completionRequested: false }); assert.equal(v5?.version, 6); assert.equal(v5?.steps[0]?.id, "legacy-1"); assert.equal("workstreams" in (v5 ?? {}), false); assert.equal("parallelRun" in (v5 ?? {}), false); });
test("version-6 restore strips unknown retired fields", () => { const restored = migratePlanState({ ...update(), workstreams: [{ id: "stale" }], parallelRun: { id: "stale" } }); assert.equal("workstreams" in (restored ?? {}), false); assert.equal("parallelRun" in (restored ?? {}), false); });
