# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x901B1C1D"
export THEME_BAR_TEXT="0xFFFFFFF0"
export THEME_BAR_TEXT_INACTIVE="0x80FFFFF0"
export THEME_BORDER_ACTIVE="0xB3FFFFF0"
export THEME_BORDER_INACTIVE="0xFF748FA6"
