# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90141517"
export THEME_BAR_TEXT="0xFFFFECFF"
export THEME_BAR_TEXT_INACTIVE="0x80FFECFF"
export THEME_BORDER_ACTIVE="0xB3FFECFF"
export THEME_BORDER_INACTIVE="0xFFC4959C"
