# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7f79ac,fg+:#fffaf3,bg:-1,bg+:-1,hl:#eb6f92,hl+:#ea9d34:bold,gutter:-1,border:#232136,separator:#232136,scrollbar:#232136,preview-fg:#fffaf3,preview-bg:-1,preview-border:#232136,preview-scrollbar:#232136,prompt:#f6c177,pointer:#ea9d34,marker:#eb6f92,spinner:#ea9a97,info:#7f79ac,header:#7f79ac,query:#3e8fb0,disabled:#7f79ac,label:#7f79ac'
export THEME_MOOR_HINT='ESC[38;2;127;121;172m'
export THEME_RGB_TEXT_MUTED='127 121 172'
export THEME_RGB_ACCENT_TERTIARY='235 111 146'
export THEME_RGB_ACCENT_AMBER='234 154 151'
export THEME_RGB_ACCENT_PRIMARY='234 157 52'
