# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#817882,fg+:#eeeeff,bg:-1,bg+:-1,hl:#6d748c,hl+:#b39066:bold,gutter:-1,border:#777d77,separator:#777d77,scrollbar:#777d77,preview-fg:#eeeeff,preview-bg:-1,preview-border:#777d77,preview-scrollbar:#777d77,prompt:#7a8aa6,pointer:#b39066,marker:#6d748c,spinner:#b5b3a5,info:#817882,header:#817882,query:#eeeeff,disabled:#817882,label:#817882'
export THEME_MOOR_HINT='ESC[38;2;129;120;130m'
export THEME_RGB_TEXT_MUTED='129 120 130'
export THEME_RGB_ACCENT_TERTIARY='109 116 140'
export THEME_RGB_ACCENT_AMBER='181 179 165'
export THEME_RGB_ACCENT_PRIMARY='179 144 102'
