# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x901E1D23"
export THEME_BAR_TEXT="0xFFDED7D0"
export THEME_BAR_TEXT_INACTIVE="0x80DED7D0"
export THEME_BORDER_ACTIVE="0xB3DED7D0"
export THEME_BORDER_INACTIVE="0xFF2E2930"
