#!/bin/sh

set -e

if pgrep -f "tmux.*display-menu" > /dev/null 2>&1; then
    pkill -f "tmux.*display-menu"
    exit 0
fi

tmux list-windows -F '#{window_index} #{window_name}' \
| awk 'BEGIN {ORS=" "} {print $2, $1, "\"select-window -t", $1 "\""}' \
| xargs tmux display-menu -T "choose window" -b "rounded"
