# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#cfa18c,fg+:#e9e9ff,bg:-1,bg+:-1,hl:#cfa18c,hl+:#87a1e6:bold,gutter:-1,border:#90aba0,separator:#90aba0,scrollbar:#90aba0,preview-fg:#e9e9ff,preview-bg:-1,preview-border:#90aba0,preview-scrollbar:#90aba0,prompt:#8a88d1,pointer:#87a1e6,marker:#cfa18c,spinner:#171719,info:#cfa18c,header:#cfa18c,query:#cf9dbd,disabled:#cfa18c,label:#cfa18c'
export THEME_MOOR_HINT='ESC[38;2;207;161;140m'
export THEME_RGB_TEXT_MUTED='207 161 140'
export THEME_RGB_ACCENT_TERTIARY='207 161 140'
export THEME_RGB_ACCENT_AMBER='23 23 25'
export THEME_RGB_ACCENT_PRIMARY='135 161 230'
