# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#d5ad9a,fg+:#e9e9ff,bg:-1,bg+:-1,hl:#cfa18c,hl+:#87a1e6:bold,gutter:-1,border:#90aba0,separator:#90aba0,scrollbar:#90aba0,preview-fg:#e9e9ff,preview-bg:-1,preview-border:#90aba0,preview-scrollbar:#90aba0,prompt:#8a88d1,pointer:#87a1e6,marker:#cfa18c,spinner:#e9e9ff,info:#d5ad9a,header:#d5ad9a,query:#cf9dbd,disabled:#d5ad9a,label:#d5ad9a'
export THEME_MOOR_HINT='ESC[38;2;213;173;154m'
export THEME_RGB_TEXT_MUTED='213 173 154'
export THEME_RGB_ACCENT_TERTIARY='207 161 140'
export THEME_RGB_ACCENT_AMBER='233 233 255'
export THEME_RGB_ACCENT_PRIMARY='135 161 230'
