# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#778a94,fg+:#f2fffc,bg:-1,bg+:-1,hl:#ffed72,hl+:#ff6d7e:bold,gutter:-1,border:#273136,separator:#273136,scrollbar:#273136,preview-fg:#f2fffc,preview-bg:-1,preview-border:#273136,preview-scrollbar:#273136,prompt:#ffb270,pointer:#ff6d7e,marker:#ffed72,spinner:#161b1e,info:#778a94,header:#778a94,query:#7cd5f1,disabled:#778a94,label:#778a94'
export THEME_MOOR_HINT='ESC[38;2;119;138;148m'
export THEME_RGB_TEXT_MUTED='119 138 148'
export THEME_RGB_ACCENT_TERTIARY='255 237 114'
export THEME_RGB_ACCENT_AMBER='22 27 30'
export THEME_RGB_ACCENT_PRIMARY='255 109 126'
