# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#3a4449,fg+:#f2fffc,bg:-1,bg+:-1,hl:#ffed72,hl+:#ff6d7e:bold,gutter:-1,border:#273136,separator:#273136,scrollbar:#273136,preview-fg:#f2fffc,preview-bg:-1,preview-border:#273136,preview-scrollbar:#273136,prompt:#ffb270,pointer:#ff6d7e,marker:#ffed72,spinner:#1d2528,info:#3a4449,header:#3a4449,query:#7cd5f1,disabled:#3a4449,label:#3a4449'
export THEME_MOOR_HINT='ESC[38;2;58;68;73m'
export THEME_RGB_TEXT_MUTED='58 68 73'
export THEME_RGB_ACCENT_TERTIARY='255 237 114'
export THEME_RGB_ACCENT_AMBER='29 37 40'
export THEME_RGB_ACCENT_PRIMARY='255 109 126'
