# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#a6acc9,fg+:#fffff0,bg:-1,bg+:-1,hl:#748fa6,hl+:#a69e6f:bold,gutter:-1,border:#748fa6,separator:#748fa6,scrollbar:#748fa6,preview-fg:#fffff0,preview-bg:-1,preview-border:#748fa6,preview-scrollbar:#748fa6,prompt:#b08c7d,pointer:#a69e6f,marker:#748fa6,spinner:#fffff0,info:#a6acc9,header:#a6acc9,query:#868db5,disabled:#a6acc9,label:#a6acc9'
export THEME_MOOR_HINT='ESC[38;2;166;172;201m'
export THEME_RGB_TEXT_MUTED='166 172 201'
export THEME_RGB_ACCENT_TERTIARY='116 143 166'
export THEME_RGB_ACCENT_AMBER='255 255 240'
export THEME_RGB_ACCENT_PRIMARY='166 158 111'
