# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90161616"
export THEME_BAR_TEXT="0xFFF2F4F8"
export THEME_BAR_TEXT_INACTIVE="0x80F2F4F8"
export THEME_BORDER_ACTIVE="0xB3F2F4F8"
export THEME_BORDER_INACTIVE="0xFF525253"
