# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90191515"
export THEME_BAR_TEXT="0xFFFFF1F3"
export THEME_BAR_TEXT_INACTIVE="0x80FFF1F3"
export THEME_BORDER_ACTIVE="0xB3FFF1F3"
export THEME_BORDER_INACTIVE="0xFF2C2525"
