# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#403838,fg+:#fff1f3,bg:-1,bg+:-1,hl:#f38d70,hl+:#fd6883:bold,gutter:-1,border:#2c2525,separator:#2c2525,scrollbar:#2c2525,preview-fg:#fff1f3,preview-bg:-1,preview-border:#2c2525,preview-scrollbar:#2c2525,prompt:#f9cc6c,pointer:#fd6883,marker:#f38d70,spinner:#211c1c,info:#403838,header:#403838,query:#adda78,disabled:#403838,label:#403838'
export THEME_MOOR_HINT='ESC[38;2;64;56;56m'
export THEME_RGB_TEXT_MUTED='64 56 56'
export THEME_RGB_ACCENT_TERTIARY='243 141 112'
export THEME_RGB_ACCENT_AMBER='33 28 28'
export THEME_RGB_ACCENT_PRIMARY='253 104 131'
