# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90171719"
export THEME_BAR_TEXT="0xFFE9E9FF"
export THEME_BAR_TEXT_INACTIVE="0x80E9E9FF"
export THEME_BORDER_ACTIVE="0xB3E9E9FF"
export THEME_BORDER_INACTIVE="0xFF90ABA0"
