# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90131313"
export THEME_BAR_TEXT="0xFFC9C7CD"
export THEME_BAR_TEXT_INACTIVE="0x80C9C7CD"
export THEME_BORDER_ACTIVE="0xB3B4B1BA"
export THEME_BORDER_INACTIVE="0xFF27272A"
