# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90131313"
export THEME_BAR_TEXT="0xFFF7F1FF"
export THEME_BAR_TEXT_INACTIVE="0x80F7F1FF"
export THEME_BORDER_ACTIVE="0xB3F7F1FF"
export THEME_BORDER_INACTIVE="0xFF222222"
