# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7d8295,fg+:#f0ecfe,bg:-1,bg+:-1,hl:#7dc2c7,hl+:#fe9f7c:bold,gutter:-1,border:#272935,separator:#272935,scrollbar:#272935,preview-fg:#f0ecfe,preview-bg:-1,preview-border:#272935,preview-scrollbar:#272935,prompt:#d2b45f,pointer:#fe9f7c,marker:#7dc2c7,spinner:#cf8164,info:#7d8295,header:#7d8295,query:#c6aed7,disabled:#7d8295,label:#7d8295'
export THEME_MOOR_HINT='ESC[38;2;125;130;149m'
export THEME_RGB_TEXT_MUTED='125 130 149'
export THEME_RGB_ACCENT_TERTIARY='125 194 199'
export THEME_RGB_ACCENT_AMBER='207 129 100'
export THEME_RGB_ACCENT_PRIMARY='254 159 124'
