# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#6c6874,fg+:#c9c7cd,bg:-1,bg+:-1,hl:#e29eca,hl+:#ea83a5:bold,gutter:-1,border:#27272a,separator:#27272a,scrollbar:#27272a,preview-fg:#c9c7cd,preview-bg:-1,preview-border:#27272a,preview-scrollbar:#27272a,prompt:#92a2d5,pointer:#ea83a5,marker:#e29eca,spinner:#e6b99d,info:#6c6874,header:#6c6874,query:#b4b1ba,disabled:#6c6874,label:#6c6874'
export THEME_MOOR_HINT='ESC[38;2;108;104;116m'
export THEME_RGB_TEXT_MUTED='108 104 116'
export THEME_RGB_ACCENT_TERTIARY='226 158 202'
export THEME_RGB_ACCENT_AMBER='230 185 157'
export THEME_RGB_ACCENT_PRIMARY='234 131 165'
