# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#758795,fg+:#fffbef,bg:-1,bg+:-1,hl:#f85552,hl+:#dfa000:bold,gutter:-1,border:#272e33,separator:#272e33,scrollbar:#272e33,preview-fg:#fffbef,preview-bg:-1,preview-border:#272e33,preview-scrollbar:#272e33,prompt:#f57d26,pointer:#dfa000,marker:#f85552,spinner:#35a77c,info:#758795,header:#758795,query:#8da101,disabled:#758795,label:#758795'
export THEME_MOOR_HINT='ESC[38;2;117;135;149m'
export THEME_RGB_TEXT_MUTED='117 135 149'
export THEME_RGB_ACCENT_TERTIARY='248 85 82'
export THEME_RGB_ACCENT_AMBER='53 167 124'
export THEME_RGB_ACCENT_PRIMARY='223 160 0'
