# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90131314"
export THEME_BAR_TEXT="0xFFFAFAFA"
export THEME_BAR_TEXT_INACTIVE="0x80FAFAFA"
export THEME_BORDER_ACTIVE="0xB3FAFAFA"
export THEME_BORDER_INACTIVE="0xFF27272A"
