# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#5c8c90,fg+:#eeeeee,bg:-1,bg+:-1,hl:#d96f3e,hl+:#ff8349:bold,gutter:-1,border:#282a30,separator:#282a30,scrollbar:#282a30,preview-fg:#eeeeee,preview-bg:-1,preview-border:#282a30,preview-scrollbar:#282a30,prompt:#ff9664,pointer:#ff8349,marker:#d96f3e,spinner:#fdb292,info:#5c8c90,header:#5c8c90,query:#e85c51,disabled:#5c8c90,label:#5c8c90'
export THEME_MOOR_HINT='ESC[38;2;92;140;144m'
export THEME_RGB_TEXT_MUTED='92 140 144'
export THEME_RGB_ACCENT_TERTIARY='217 111 62'
export THEME_RGB_ACCENT_AMBER='253 178 146'
export THEME_RGB_ACCENT_PRIMARY='255 131 73'
