# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#6e6e8e,fg+:#ecece8,bg:-1,bg+:-1,hl:#cc6d00,hl+:#e98a00:bold,gutter:-1,border:#181616,separator:#181616,scrollbar:#181616,preview-fg:#ecece8,preview-bg:-1,preview-border:#181616,preview-scrollbar:#181616,prompt:#de9800,pointer:#e98a00,marker:#cc6d00,spinner:#d7474b,info:#6e6e8e,header:#6e6e8e,query:#ff9e3b,disabled:#6e6e8e,label:#6e6e8e'
export THEME_MOOR_HINT='ESC[38;2;110;110;142m'
export THEME_RGB_TEXT_MUTED='110 110 142'
export THEME_RGB_ACCENT_TERTIARY='204 109 0'
export THEME_RGB_ACCENT_AMBER='215 71 75'
export THEME_RGB_ACCENT_PRIMARY='233 138 0'
