# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x9019181A"
export THEME_BAR_TEXT="0xFFFCFCFA"
export THEME_BAR_TEXT_INACTIVE="0x80FCFCFA"
export THEME_BORDER_ACTIVE="0xB3FCFCFA"
export THEME_BORDER_INACTIVE="0xFF2D2A2E"
