#!/bin/sh

set -e

# Disable glob expansion to prevent * in session names from expanding to files
set -f

# Get absolute bottom-right coordinates of the window
client_width=$(tmux display-message -p '#{client_width}')
client_height=$(tmux display-message -p '#{client_height}')

# Build menu items: sessions list + separator + new session/window options
sessions=$(tmux list-sessions -F '#S' | awk 'BEGIN {ORS=" "} {print $1, NR, "\"switch-client -t", $1 "\""}')

# Use eval to properly handle the command
# Multiple separator lines (empty name/key/command) create more spacing
# Position at absolute bottom right corner of window
eval "tmux display-menu -M -O -T \"#[align=centre]choose session\" -b rounded -x $client_width -y 1 \
    $sessions \
    \"\" \"\" \"\" \
    \"\" \"\" \"\" \
    \"rename session\" r \"command-prompt -I '#S' 'rename-session \\\"%%\\\"'\" \
    \"new session\" s \"command-prompt -p 'new session:' 'new-session -s \\\"%%\\\"'\" \
    \"new window\" w \"new-window\""
