#!/bin/sh

set -e

current_session=$(tmux display-message -p '#{session_name}')

tmux list-panes -a -F '#{session_name}|#{window_index}|#{window_name}|#{pane_index}|#{pane_title}|#{pane_current_command}|#{pane_current_path}' \
| awk -F'|' -v HOME="$HOME" -v SESSION="$current_session" 'BEGIN {ORS=" "} $1 == SESSION {
    path = $7
    sub("^" HOME, "~", path)
    print "\"" $2 " [" $3 "]{" $4 "} [" $5 "] [" $6 "] (" path ")\" \"\" \"switch-client -t " SESSION ":" $2 "." $4 "\""
}' \
| xargs tmux display-menu -T "#[align=centre]choose pane" -b "rounded"
