#!/usr/bin/env bash

set -euo pipefail

literal_label() {
  local value="$1"
  value=${value//$'\n'/ }
  value=${value//$'\r'/ }
  value=${value//$'\t'/ }
  value=$(printf '%s' "$value" | LC_ALL=C tr -d '\001-\010\013\014\016-\037\177')
  printf '%s' "${value//#/##}"
}

client_width=$(tmux display-message -p '#{client_width}')
menu=()
float=()
other=()
while IFS=$'\t' read -r sid name; do
  [ -n "$sid" ] || continue
  row="$(literal_label "$name")"$'\t'"$sid"
  if [[ "$name" == float ]]; then float+=("$row"); else other+=("$row"); fi
done < <(tmux list-sessions -O creation -F $'#{session_id}\t#{session_name}')

index=1
append_rows() {
  local row name sid key
  for row in "$@"; do
    name=${row%%$'\t'*}
    sid=${row#*$'\t'}
    key=$index
    [ "$index" -le 9 ] || key=""
    menu+=("$name" "$key" "switch-client -t $sid")
    index=$((index + 1))
  done
}
((${#float[@]} == 0)) || append_rows "${float[@]}"
((${#other[@]} == 0)) || append_rows "${other[@]}"

menu+=("" "" "" "" "" ""
  "rename session" r "command-prompt -I '#S' 'rename-session \"%%\"'"
  "new session" s "command-prompt -p 'new session:' 'new-session -s \"%%\"'"
  "new window" w "new-window")

tmux display-menu -M -O -T '#[align=centre]choose session' -b rounded \
  -x "$client_width" -y 1 "${menu[@]}"
