#!/bin/zsh

set -e

CURRENT_PANE="$(tmux display-message -p -F "#{session_name}")"

width=${2:-100%}
height=${2:-40%}

if echo "$CURRENT_PANE" | grep -q '^ephemeral.*'; then
    tmux kill-session
else
    if [ "$1" = "single" ]; then
        tmux popup -d '#{pane_current_path}' -xM -yS -w$width -h$height -S "fg=#90a0b5" -E "tmux attach -t 'ephemeral' || tmux new -s 'ephemeral'" || true
    else
        tmux popup -d '#{pane_current_path}' -xM -yS -w$width -h$height -S "fg=#90a0b5" -E "tmux attach -t ephemeral || tmux new -s 'ephemeral'" || true
    fi
fi
