#!/bin/sh

set -e

# original session list:
# tmux list-sessions -F '#S' \
# | awk 'BEGIN {ORS=" "} {print $1, NR, "\"switch-client -t", $1 "\""}' \
# | xargs tmux display-menu -O -M -T "choose session" -x M -y W

# Disable glob expansion to prevent * in session names from expanding to files
set -f

# Build menu items: sessions list + separator + new session/window options
sessions=$(tmux list-sessions -F '#S' | awk 'BEGIN {ORS=" "} {print $1, NR, "\"switch-client -t", $1 "\""}')

# Use eval to properly handle the command
# Multiple separator lines (empty name/key/command) create more spacing
# Removed -O flag to close menu when mouse is released (like window menu)
eval "tmux display-menu -M -T \"#[align=centre]choose session\" -x M -y W \
    $sessions \
    \"\" \"\" \"\" \
    \"\" \"\" \"\" \
    \"rename session\" r \"command-prompt -I '#S' 'rename-session \\\"%%\\\"'\" \
    \"new session\" s \"command-prompt -p 'new session:' 'new-session -s \\\"%%\\\"'\" \
    \"new window\" w \"new-window\""
