#!/bin/sh

set -e
set -f

current_session_id=$(tmux display-message -p '#{session_id}')

tmux list-panes -a -F '#{session_id}|#{session_name}|#{window_index}|#{window_name}|#{pane_index}|#{pane_title}|#{pane_current_command}|#{pane_current_path}' \
| awk -F'|' -v HOME="$HOME" -v SESSION_ID="$current_session_id" '
BEGIN {
    ORS = " "
    KEYS = "1234567890abcdefghijklmnopqrstuvwxyz"
    global_key_idx = 0
}
$1 != SESSION_ID {
    sid = $1; sname = $2; win = $3; wname = $4; pane = $5; pname = $6; cmd = $7; path = $8

    sub("^" HOME, "~", path)
    if (pname == "") pname = "-"
    if (length(wname) > 18) wname = substr(wname, 1, 15) "..."
    if (length(cmd) > 12) cmd = substr(cmd, 1, 9) "..."
    if (length(pname) > 18) pname = substr(pname, 1, 15) "..."
    if (length(path) > 36) path = substr(path, 1, 33) "..."

    # Track sessions
    if (!(sid in seen_session)) {
        session_order[++session_count] = sid
        seen_session[sid] = sname
        session_win_count[sid] = 0
    }
    # Track windows
    wkey = sid ":" win
    if (!(wkey in seen_window)) {
        seen_window[wkey] = wname
        session_win_count[sid]++
        win_order[sid, ++win_count[sid]] = win
    }
    # Store pane items
    pane_items[++pane_count] = sid SUBSEP wkey SUBSEP pane
    pane_label[pane_count] = sprintf("%-4s %-18s %-12s %-18s %-36s", win "." pane, wname, cmd, pname, path)
    pane_cmd[pane_count] = "switch-client -t " sname ":" win "." pane
}
END {
    if (session_count == 0) {
        print "\"No other panes\" \"\" \"\""
        exit
    }
    for (s = 1; s <= session_count; s++) {
        sid = session_order[s]
        sname = seen_session[sid]
        nw = session_win_count[sid]

        # Session header row
        print "\"" sname " [" nw " windows]\" \"\" \"switch-client -t " sname "\""

        # Window quick-jump rows
        for (w = 1; w <= win_count[sid]; w++) {
            win = win_order[sid, w]
            wkey = sid ":" win
            wname = seen_window[wkey]
            global_key_idx++
            key = (global_key_idx <= length(KEYS)) ? substr(KEYS, global_key_idx, 1) : ""
            label = sprintf("%-4s %-18s", win, wname)
            print "\"" label "\" \"" key "\" \"switch-client -t " sname ":" win "\""
        }

        # Separator + pane details
        print "\"\" \"\" \"\""
        print "\"pane information\" \"\" \"\""
        print "\"" sprintf("%-4s %-18s %-12s %-18s %-36s", "WIN", "WINDOW_NAME", "COMMAND", "PANE_NAME", "PATH") "\" \"\" \"\""

        for (p = 1; p <= pane_count; p++) {
            split(pane_items[p], a, SUBSEP)
            if (a[1] == sid) {
                print "\"" pane_label[p] "\" \"\" \"" pane_cmd[p] "\""
            }
        }

        # Separator between sessions
        print "\"\" \"\" \"\""
    }
}' \
| xargs tmux display-menu -T "#[align=centre]other windows" -b "rounded"
