#!/bin/sh

set -e

CURRENT_PANE="$(tmux display-message -p '#{pane_id}')"
CURRENT_SESSION="$(tmux display-message -p '#{session_name}')"

tmux list-windows -F '#{window_index}|#{window_name}' \
| awk -F'|' -v pane="$CURRENT_PANE" -v session="$CURRENT_SESSION" 'BEGIN { ORS = " " } {
    idx = $1
    wname = $2
    print "\"" wname "\"", idx, "\"join-pane -s", pane, "-t", session ":" idx "\""
}' | xargs tmux display-menu -T "move pane to window" -b "rounded"
