# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x900E1415"
export THEME_BAR_TEXT="0xFFCECECE"
export THEME_BAR_TEXT_INACTIVE="0x80CECECE"
export THEME_BORDER_ACTIVE="0xB3CECECE"
export THEME_BORDER_INACTIVE="0xFF30464A"
