#!/usr/bin/env sh
# Toggle wrapping only in this nnn process's verified preview pane.
self=${TMUX_PANE:-}
[ -n "$self" ] || exit 0
server_id=${TMUX#*,}; server_id=${server_id%%,*}
map="${TMPDIR:-/tmp}/nnn-preview-panes/$server_id/$self"
other=$(cat "$map" 2>/dev/null)
[ -n "$other" ] || exit 0

self_window=$(tmux display-message -p -t "$self" '#{window_id}' 2>/dev/null) || exit 0
identity=$(tmux display-message -p -t "$other" '#{@nnn_preview}|#{window_id}' 2>/dev/null) || {
    rm -f -- "$map"
    exit 0
}
[ "$identity" = "1|$self_window" ] || {
    rm -f -- "$map"
    exit 0
}

case "$NNN_PAGER" in
    moor*) tmux send-keys -t "$other" 'w' ;;
    *) tmux send-keys -t "$other" -l -- '-S' ;;
esac
