# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90171614"
export THEME_BAR_TEXT="0xFFFFEAEA"
export THEME_BAR_TEXT_INACTIVE="0x80FFEAEA"
export THEME_BORDER_ACTIVE="0xB3FFEAEA"
export THEME_BORDER_INACTIVE="0xFF9E6057"
