# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#363636,fg+:#f0f0f0,bg:-1,bg+:-1,hl:#aca98a,hl+:#ac8aac:bold,gutter:-1,border:#222222,separator:#222222,scrollbar:#222222,preview-fg:#f0f0f0,preview-bg:-1,preview-border:#222222,preview-scrollbar:#222222,prompt:#8aabac,pointer:#ac8aac,marker:#aca98a,spinner:#050505,info:#363636,header:#363636,query:#ac9d8a,disabled:#363636,label:#363636'
export THEME_MOOR_HINT='ESC[38;2;54;54;54m'
export THEME_RGB_TEXT_MUTED='54 54 54'
export THEME_RGB_ACCENT_TERTIARY='172 169 138'
export THEME_RGB_ACCENT_AMBER='5 5 5'
export THEME_RGB_ACCENT_PRIMARY='172 138 172'
