# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7b7b7b,fg+:#f0f0f0,bg:-1,bg+:-1,hl:#aca98a,hl+:#ac8aac:bold,gutter:-1,border:#222222,separator:#222222,scrollbar:#222222,preview-fg:#f0f0f0,preview-bg:-1,preview-border:#222222,preview-scrollbar:#222222,prompt:#8aabac,pointer:#ac8aac,marker:#aca98a,spinner:#8aac8b,info:#7b7b7b,header:#7b7b7b,query:#ac9d8a,disabled:#7b7b7b,label:#7b7b7b'
export THEME_MOOR_HINT='ESC[38;2;123;123;123m'
export THEME_RGB_TEXT_MUTED='123 123 123'
export THEME_RGB_ACCENT_TERTIARY='172 169 138'
export THEME_RGB_ACCENT_AMBER='138 172 139'
export THEME_RGB_ACCENT_PRIMARY='172 138 172'
