# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#32353e,fg+:#f0ecfe,bg:-1,bg+:-1,hl:#fead90,hl+:#fe9f7c:bold,gutter:-1,border:#272935,separator:#272935,scrollbar:#272935,preview-fg:#f0ecfe,preview-bg:-1,preview-border:#272935,preview-scrollbar:#272935,prompt:#d2b45f,pointer:#fe9f7c,marker:#fead90,spinner:#b8a161,info:#32353e,header:#32353e,query:#cf8164,disabled:#32353e,label:#32353e'
export THEME_MOOR_HINT='ESC[38;2;50;53;62m'
export THEME_RGB_TEXT_MUTED='50 53 62'
export THEME_RGB_ACCENT_TERTIARY='254 173 144'
export THEME_RGB_ACCENT_AMBER='184 161 97'
export THEME_RGB_ACCENT_PRIMARY='254 159 124'
