# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7b7d8f,fg+:#f0ecfe,bg:-1,bg+:-1,hl:#94cdd1,hl+:#fead90:bold,gutter:-1,border:#272935,separator:#272935,scrollbar:#272935,preview-fg:#f0ecfe,preview-bg:-1,preview-border:#272935,preview-scrollbar:#272935,prompt:#dbc380,pointer:#fead90,marker:#94cdd1,spinner:#d59076,info:#7b7d8f,header:#7b7d8f,query:#cdb6dd,disabled:#7b7d8f,label:#7b7d8f'
export THEME_MOOR_HINT='ESC[38;2;123;125;143m'
export THEME_RGB_TEXT_MUTED='123 125 143'
export THEME_RGB_ACCENT_TERTIARY='148 205 209'
export THEME_RGB_ACCENT_AMBER='213 144 118'
export THEME_RGB_ACCENT_PRIMARY='254 173 144'
