# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#656a80,fg+:#BEBEBE,bg:-1,bg+:-1,hl:#bb9dbd,hl+:#d8647e:bold,gutter:-1,border:#383848,separator:#383848,scrollbar:#383848,preview-fg:#BEBEBE,preview-bg:-1,preview-border:#383848,preview-scrollbar:#383848,prompt:#aeaed1,pointer:#d8647e,marker:#bb9dbd,spinner:#f3be7c,info:#656a80,header:#656a80,query:#bebedb,disabled:#656a80,label:#656a80'
export THEME_MOOR_HINT='ESC[38;2;101;106;128m'
export THEME_RGB_TEXT_MUTED='101 106 128'
export THEME_RGB_ACCENT_TERTIARY='187 157 189'
export THEME_RGB_ACCENT_AMBER='243 190 124'
export THEME_RGB_ACCENT_PRIMARY='216 100 126'
