# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x901D1B20"
export THEME_BAR_TEXT="0xFFE6E0E9"
export THEME_BAR_TEXT_INACTIVE="0x80E6E0E9"
export THEME_BORDER_ACTIVE="0xB3E6E0E9"
export THEME_BORDER_INACTIVE="0xFF2B292F"
