# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#363537,fg+:#f7f1ff,bg:-1,bg+:-1,hl:#fce566,hl+:#fd9353:bold,gutter:-1,border:#222222,separator:#222222,scrollbar:#222222,preview-fg:#f7f1ff,preview-bg:-1,preview-border:#222222,preview-scrollbar:#222222,prompt:#fc618d,pointer:#fd9353,marker:#fce566,spinner:#191919,info:#363537,header:#363537,query:#5ad4e6,disabled:#363537,label:#363537'
export THEME_MOOR_HINT='ESC[38;2;54;53;55m'
export THEME_RGB_TEXT_MUTED='54 53 55'
export THEME_RGB_ACCENT_TERTIARY='252 229 102'
export THEME_RGB_ACCENT_AMBER='25 25 25'
export THEME_RGB_ACCENT_PRIMARY='253 147 83'
