# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7c7a7f,fg+:#f7f1ff,bg:-1,bg+:-1,hl:#fce566,hl+:#fd9353:bold,gutter:-1,border:#222222,separator:#222222,scrollbar:#222222,preview-fg:#f7f1ff,preview-bg:-1,preview-border:#222222,preview-scrollbar:#222222,prompt:#fc618d,pointer:#fd9353,marker:#fce566,spinner:#131313,info:#7c7a7f,header:#7c7a7f,query:#5ad4e6,disabled:#7c7a7f,label:#7c7a7f'
export THEME_MOOR_HINT='ESC[38;2;124;122;127m'
export THEME_RGB_TEXT_MUTED='124 122 127'
export THEME_RGB_ACCENT_TERTIARY='252 229 102'
export THEME_RGB_ACCENT_AMBER='19 19 19'
export THEME_RGB_ACCENT_PRIMARY='253 147 83'
