# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x901E2326"
export THEME_BAR_TEXT="0xFFFFFBEF"
export THEME_BAR_TEXT_INACTIVE="0x80FFFBEF"
export THEME_BORDER_ACTIVE="0xB3FFFBEF"
export THEME_BORDER_INACTIVE="0xFF272E33"
