# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x900D0C0C"
export THEME_BAR_TEXT="0xFFECECE8"
export THEME_BAR_TEXT_INACTIVE="0x80ECECE8"
export THEME_BORDER_ACTIVE="0xB3ECECE8"
export THEME_BORDER_INACTIVE="0xFF181616"
