#!/bin/bash

options=(
	style=square
	width=4.0
	hidpi=off
  ax_focus=off
  active_color=0xffaeaed1
	inactive_color=0xff1c1c24
)

# Absolute path: this script can be sourced from environments without
# /opt/homebrew/bin on $PATH (e.g. Hammerspoon's GUI process env).
/opt/homebrew/bin/borders "${options[@]}"
