# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#36343b,fg+:#e6e0e9,bg:-1,bg+:-1,hl:#efb8c8,hl+:#d0bcff:bold,gutter:-1,border:#2b292f,separator:#2b292f,scrollbar:#2b292f,preview-fg:#e6e0e9,preview-bg:-1,preview-border:#2b292f,preview-scrollbar:#2b292f,prompt:#f2b8b5,pointer:#d0bcff,marker:#efb8c8,spinner:#211f26,info:#36343b,header:#36343b,query:#ccc2dc,disabled:#36343b,label:#36343b'
export THEME_MOOR_HINT='ESC[38;2;54;52;59m'
export THEME_RGB_TEXT_MUTED='54 52 59'
export THEME_RGB_ACCENT_TERTIARY='239 184 200'
export THEME_RGB_ACCENT_AMBER='33 31 38'
export THEME_RGB_ACCENT_PRIMARY='208 188 255'
