# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#847f8f,fg+:#e6e0e9,bg:-1,bg+:-1,hl:#efb8c8,hl+:#d0bcff:bold,gutter:-1,border:#2b292f,separator:#2b292f,scrollbar:#2b292f,preview-fg:#e6e0e9,preview-bg:-1,preview-border:#2b292f,preview-scrollbar:#2b292f,prompt:#f2b8b5,pointer:#d0bcff,marker:#efb8c8,spinner:#1d1b20,info:#847f8f,header:#847f8f,query:#ccc2dc,disabled:#847f8f,label:#847f8f'
export THEME_MOOR_HINT='ESC[38;2;132;127;143m'
export THEME_RGB_TEXT_MUTED='132 127 143'
export THEME_RGB_ACCENT_TERTIARY='239 184 200'
export THEME_RGB_ACCENT_AMBER='29 27 32'
export THEME_RGB_ACCENT_PRIMARY='208 188 255'
