# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#ae8a9d,fg+:#fffbef,bg:-1,bg+:-1,hl:#f85552,hl+:#dfa000:bold,gutter:-1,border:#333c43,separator:#333c43,scrollbar:#333c43,preview-fg:#fffbef,preview-bg:-1,preview-border:#333c43,preview-scrollbar:#333c43,prompt:#f57d26,pointer:#dfa000,marker:#f85552,spinner:#35a77c,info:#ae8a9d,header:#ae8a9d,query:#8da101,disabled:#ae8a9d,label:#ae8a9d'
export THEME_MOOR_HINT='ESC[38;2;174;138;157m'
export THEME_RGB_TEXT_MUTED='174 138 157'
export THEME_RGB_ACCENT_TERTIARY='248 85 82'
export THEME_RGB_ACCENT_AMBER='53 167 124'
export THEME_RGB_ACCENT_PRIMARY='223 160 0'
