# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90000000"
export THEME_BAR_TEXT="0xFFFFFFFF"
export THEME_BAR_TEXT_INACTIVE="0x80FFFFFF"
export THEME_BORDER_ACTIVE="0xB3FFFFFF"
export THEME_BORDER_INACTIVE="0xFF151515"
