# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#8983ae,fg+:#eae8ff,bg:-1,bg+:-1,hl:#f6c177,hl+:#e6a852:bold,gutter:-1,border:#2d2a45,separator:#2d2a45,scrollbar:#2d2a45,preview-fg:#eae8ff,preview-bg:-1,preview-border:#2d2a45,preview-scrollbar:#2d2a45,prompt:#d84f76,pointer:#e6a852,marker:#f6c177,spinner:#d871a6,info:#8983ae,header:#8983ae,query:#eb6f92,disabled:#8983ae,label:#8983ae'
export THEME_MOOR_HINT='ESC[38;2;137;131;174m'
export THEME_RGB_TEXT_MUTED='137 131 174'
export THEME_RGB_ACCENT_TERTIARY='246 193 119'
export THEME_RGB_ACCENT_AMBER='216 113 166'
export THEME_RGB_ACCENT_PRIMARY='230 168 82'
