# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90131A24"
export THEME_BAR_TEXT="0xFFDFDFE0"
export THEME_BAR_TEXT_INACTIVE="0x80DFDFE0"
export THEME_BORDER_ACTIVE="0xB3DFDFE0"
export THEME_BORDER_INACTIVE="0xFF212E3F"
