# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90050505"
export THEME_BAR_TEXT="0xFFF0F0F0"
export THEME_BAR_TEXT_INACTIVE="0x80F0F0F0"
export THEME_BORDER_ACTIVE="0xB3F0F0F0"
export THEME_BORDER_INACTIVE="0xFF222222"
