# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90191724"
export THEME_BAR_TEXT="0xFFFFFAF3"
export THEME_BAR_TEXT_INACTIVE="0x80FFFAF3"
export THEME_BORDER_ACTIVE="0xB3FFFAF3"
export THEME_BORDER_INACTIVE="0xFF232136"
