# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#6987b1,fg+:#dfdfe0,bg:-1,bg+:-1,hl:#63cdcf,hl+:#f4a261:bold,gutter:-1,border:#212e3f,separator:#212e3f,scrollbar:#212e3f,preview-fg:#dfdfe0,preview-bg:-1,preview-border:#212e3f,preview-scrollbar:#212e3f,prompt:#c94f6d,pointer:#f4a261,marker:#63cdcf,spinner:#3c5372,info:#6987b1,header:#6987b1,query:#dbc074,disabled:#6987b1,label:#6987b1'
export THEME_MOOR_HINT='ESC[38;2;105;135;177m'
export THEME_RGB_TEXT_MUTED='105 135 177'
export THEME_RGB_ACCENT_TERTIARY='99 205 207'
export THEME_RGB_ACCENT_AMBER='60 83 114'
export THEME_RGB_ACCENT_PRIMARY='244 162 97'
