# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#403a36,fg+:#ece1d7,bg:-1,bg+:-1,hl:#d47766,hl+:#e49b5d:bold,gutter:-1,border:#253333,separator:#253333,scrollbar:#253333,preview-fg:#ece1d7,preview-bg:-1,preview-border:#253333,preview-scrollbar:#253333,prompt:#ebc06d,pointer:#e49b5d,marker:#d47766,spinner:#c1a78e,info:#403a36,header:#403a36,query:#7d2a2f,disabled:#403a36,label:#403a36'
export THEME_MOOR_HINT='ESC[38;2;64;58;54m'
export THEME_RGB_TEXT_MUTED='64 58 54'
export THEME_RGB_ACCENT_TERTIARY='212 119 102'
export THEME_RGB_ACCENT_AMBER='193 167 142'
export THEME_RGB_ACCENT_PRIMARY='228 155 93'
