# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90161613"
export THEME_BAR_TEXT="0xFFFDFFF1"
export THEME_BAR_TEXT_INACTIVE="0x80FDFFF1"
export THEME_BORDER_ACTIVE="0xB3FDFFF1"
export THEME_BORDER_INACTIVE="0xFF272822"
