# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x900F1C1E"
export THEME_BAR_TEXT="0xFFEEEEEE"
export THEME_BAR_TEXT_INACTIVE="0x80EEEEEE"
export THEME_BORDER_ACTIVE="0xB3EEEEEE"
export THEME_BORDER_INACTIVE="0xFF282A30"
