# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7C7E8C,fg+:#D7D7D7,bg:-1,bg+:-1,hl:#BDA9D4,hl+:#FB7DA7:bold,gutter:-1,border:#21252D,separator:#21252D,scrollbar:#21252D,preview-fg:#D7D7D7,preview-bg:-1,preview-border:#21252D,preview-scrollbar:#21252D,prompt:#AF98E6,pointer:#FB7DA7,marker:#BDA9D4,spinner:#E3CF65,info:#7C7E8C,header:#7C7E8C,query:#BBBBBB,disabled:#7C7E8C,label:#7C7E8C'
export THEME_MOOR_HINT='ESC[38;2;124;126;140m'
export THEME_RGB_TEXT_MUTED='124 126 140'
export THEME_RGB_ACCENT_TERTIARY='189 169 212'
export THEME_RGB_ACCENT_AMBER='227 207 101'
export THEME_RGB_ACCENT_PRIMARY='251 125 167'
