# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#6d9799,fg+:#f0f0f0,bg:-1,bg+:-1,hl:#aca98a,hl+:#ac8aac:bold,gutter:-1,border:#363636,separator:#363636,scrollbar:#363636,preview-fg:#f0f0f0,preview-bg:-1,preview-border:#363636,preview-scrollbar:#363636,prompt:#8aabac,pointer:#ac8aac,marker:#aca98a,spinner:#8aac8b,info:#6d9799,header:#6d9799,query:#ac9d8a,disabled:#6d9799,label:#6d9799'
export THEME_MOOR_HINT='ESC[38;2;109;151;153m'
export THEME_RGB_TEXT_MUTED='109 151 153'
export THEME_RGB_ACCENT_TERTIARY='172 169 138'
export THEME_RGB_ACCENT_AMBER='138 172 139'
export THEME_RGB_ACCENT_PRIMARY='172 138 172'
