# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#2f4243,fg+:#f0f0f0,bg:-1,bg+:-1,hl:#aca98a,hl+:#ac8aac:bold,gutter:-1,border:#363636,separator:#363636,scrollbar:#363636,preview-fg:#f0f0f0,preview-bg:-1,preview-border:#363636,preview-scrollbar:#363636,prompt:#8aabac,pointer:#ac8aac,marker:#aca98a,spinner:#191919,info:#2f4243,header:#2f4243,query:#ac9d8a,disabled:#2f4243,label:#2f4243'
export THEME_MOOR_HINT='ESC[38;2;47;66;67m'
export THEME_RGB_TEXT_MUTED='47 66 67'
export THEME_RGB_ACCENT_TERTIARY='172 169 138'
export THEME_RGB_ACCENT_AMBER='25 25 25'
export THEME_RGB_ACCENT_PRIMARY='172 138 172'
