# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90232831"
export THEME_BAR_TEXT="0xFFE7ECF4"
export THEME_BAR_TEXT_INACTIVE="0x80E7ECF4"
export THEME_BORDER_ACTIVE="0xB3E7ECF4"
export THEME_BORDER_INACTIVE="0xFF353A45"
