# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x900D0C0B"
export THEME_BAR_TEXT="0xFFF9F5EC"
export THEME_BAR_TEXT_INACTIVE="0x80F9F5EC"
export THEME_BORDER_ACTIVE="0xB3F9F5EC"
export THEME_BORDER_INACTIVE="0xFF38100A"
