# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7e839b,fg+:#eaf2f1,bg:-1,bg+:-1,hl:#ffd76d,hl+:#ff9b5e:bold,gutter:-1,border:#282a3a,separator:#282a3a,scrollbar:#282a3a,preview-fg:#eaf2f1,preview-bg:-1,preview-border:#282a3a,preview-scrollbar:#282a3a,prompt:#ff657a,pointer:#ff9b5e,marker:#ffd76d,spinner:#161821,info:#7e839b,header:#7e839b,query:#bad761,disabled:#7e839b,label:#7e839b'
export THEME_MOOR_HINT='ESC[38;2;126;131;155m'
export THEME_RGB_TEXT_MUTED='126 131 155'
export THEME_RGB_ACCENT_TERTIARY='255 215 109'
export THEME_RGB_ACCENT_AMBER='22 24 33'
export THEME_RGB_ACCENT_PRIMARY='255 155 94'
