# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#3a3d4b,fg+:#eaf2f1,bg:-1,bg+:-1,hl:#ffd76d,hl+:#ff9b5e:bold,gutter:-1,border:#282a3a,separator:#282a3a,scrollbar:#282a3a,preview-fg:#eaf2f1,preview-bg:-1,preview-border:#282a3a,preview-scrollbar:#282a3a,prompt:#ff657a,pointer:#ff9b5e,marker:#ffd76d,spinner:#1e1f2b,info:#3a3d4b,header:#3a3d4b,query:#bad761,disabled:#3a3d4b,label:#3a3d4b'
export THEME_MOOR_HINT='ESC[38;2;58;61;75m'
export THEME_RGB_TEXT_MUTED='58 61 75'
export THEME_RGB_ACCENT_TERTIARY='255 215 109'
export THEME_RGB_ACCENT_AMBER='30 31 43'
export THEME_RGB_ACCENT_PRIMARY='255 155 94'
