# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#44415a,fg+:#fffaf3,bg:-1,bg+:-1,hl:#eb6f92,hl+:#ea9d34:bold,gutter:-1,border:#393552,separator:#393552,scrollbar:#393552,preview-fg:#fffaf3,preview-bg:-1,preview-border:#393552,preview-scrollbar:#393552,prompt:#f6c177,pointer:#ea9d34,marker:#eb6f92,spinner:#ea9a97,info:#44415a,header:#44415a,query:#3e8fb0,disabled:#44415a,label:#44415a'
export THEME_MOOR_HINT='ESC[38;2;68;65;90m'
export THEME_RGB_TEXT_MUTED='68 65 90'
export THEME_RGB_ACCENT_TERTIARY='235 111 146'
export THEME_RGB_ACCENT_AMBER='234 154 151'
export THEME_RGB_ACCENT_PRIMARY='234 157 52'
