# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x900F0F0F"
export THEME_BAR_TEXT="0xFFEDEDED"
export THEME_BAR_TEXT_INACTIVE="0x80EDEDED"
export THEME_BORDER_ACTIVE="0xB39094A0"
export THEME_BORDER_INACTIVE="0xFF1C1C24"
