# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#808272,fg+:#fdfff1,bg:-1,bg+:-1,hl:#a6e22e,hl+:#fd971f:bold,gutter:-1,border:#272822,separator:#272822,scrollbar:#272822,preview-fg:#fdfff1,preview-bg:-1,preview-border:#272822,preview-scrollbar:#272822,prompt:#f92672,pointer:#fd971f,marker:#a6e22e,spinner:#161613,info:#808272,header:#808272,query:#66d9ef,disabled:#808272,label:#808272'
export THEME_MOOR_HINT='ESC[38;2;128;130;114m'
export THEME_RGB_TEXT_MUTED='128 130 114'
export THEME_RGB_ACCENT_TERTIARY='166 226 46'
export THEME_RGB_ACCENT_AMBER='22 22 19'
export THEME_RGB_ACCENT_PRIMARY='253 151 31'
