# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#3b3c35,fg+:#fdfff1,bg:-1,bg+:-1,hl:#a6e22e,hl+:#fd971f:bold,gutter:-1,border:#272822,separator:#272822,scrollbar:#272822,preview-fg:#fdfff1,preview-bg:-1,preview-border:#272822,preview-scrollbar:#272822,prompt:#f92672,pointer:#fd971f,marker:#a6e22e,spinner:#1d1e19,info:#3b3c35,header:#3b3c35,query:#66d9ef,disabled:#3b3c35,label:#3b3c35'
export THEME_MOOR_HINT='ESC[38;2;59;60;53m'
export THEME_RGB_TEXT_MUTED='59 60 53'
export THEME_RGB_ACCENT_TERTIARY='166 226 46'
export THEME_RGB_ACCENT_AMBER='29 30 25'
export THEME_RGB_ACCENT_PRIMARY='253 151 31'
