# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#353539,fg+:#fafafa,bg:-1,bg+:-1,hl:#e08200,hl+:#f27306:bold,gutter:-1,border:#27272a,separator:#27272a,scrollbar:#27272a,preview-fg:#fafafa,preview-bg:-1,preview-border:#27272a,preview-scrollbar:#27272a,prompt:#f2a50a,pointer:#f27306,marker:#e08200,spinner:#e05439,info:#353539,header:#353539,query:#c65c00,disabled:#353539,label:#353539'
export THEME_MOOR_HINT='ESC[38;2;53;53;57m'
export THEME_RGB_TEXT_MUTED='53 53 57'
export THEME_RGB_ACCENT_TERTIARY='224 130 0'
export THEME_RGB_ACCENT_AMBER='224 84 57'
export THEME_RGB_ACCENT_PRIMARY='242 115 6'
