# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#525253,fg+:#f2f4f8,bg:-1,bg+:-1,hl:#3ddbd9,hl+:#33b1ff:bold,gutter:-1,border:#525253,separator:#525253,scrollbar:#525253,preview-fg:#f2f4f8,preview-bg:-1,preview-border:#525253,preview-scrollbar:#525253,prompt:#08bdba,pointer:#33b1ff,marker:#3ddbd9,spinner:#42be65,info:#525253,header:#525253,query:#ee5396,disabled:#525253,label:#525253'
export THEME_MOOR_HINT='ESC[38;2;82;82;83m'
export THEME_RGB_TEXT_MUTED='82 82 83'
export THEME_RGB_ACCENT_TERTIARY='61 219 217'
export THEME_RGB_ACCENT_AMBER='66 190 101'
export THEME_RGB_ACCENT_PRIMARY='51 177 255'
