# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#a9c6c2,fg+:#ffecff,bg:-1,bg+:-1,hl:#a6a4eb,hl+:#96aff2:bold,gutter:-1,border:#c4959c,separator:#c4959c,scrollbar:#c4959c,preview-fg:#ffecff,preview-bg:-1,preview-border:#c4959c,preview-scrollbar:#c4959c,prompt:#5f86b0,pointer:#96aff2,marker:#a6a4eb,spinner:#ffecff,info:#a9c6c2,header:#a9c6c2,query:#c9aa95,disabled:#a9c6c2,label:#a9c6c2'
export THEME_MOOR_HINT='ESC[38;2;169;198;194m'
export THEME_RGB_TEXT_MUTED='169 198 194'
export THEME_RGB_ACCENT_TERTIARY='166 164 235'
export THEME_RGB_ACCENT_AMBER='255 236 255'
export THEME_RGB_ACCENT_PRIMARY='150 175 242'
