# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#9bbdb8,fg+:#ffecff,bg:-1,bg+:-1,hl:#a6a4eb,hl+:#96aff2:bold,gutter:-1,border:#c4959c,separator:#c4959c,scrollbar:#c4959c,preview-fg:#ffecff,preview-bg:-1,preview-border:#c4959c,preview-scrollbar:#c4959c,prompt:#5f86b0,pointer:#96aff2,marker:#a6a4eb,spinner:#141517,info:#9bbdb8,header:#9bbdb8,query:#c9aa95,disabled:#9bbdb8,label:#9bbdb8'
export THEME_MOOR_HINT='ESC[38;2;155;189;184m'
export THEME_RGB_TEXT_MUTED='155 189 184'
export THEME_RGB_ACCENT_TERTIARY='166 164 235'
export THEME_RGB_ACCENT_AMBER='20 21 23'
export THEME_RGB_ACCENT_PRIMARY='150 175 242'
