# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7F737D,fg+:#DED7D0,bg:-1,bg+:-1,hl:#BDA9D4,hl+:#FF7DA3:bold,gutter:-1,border:#2E2930,separator:#2E2930,scrollbar:#2E2930,preview-fg:#DED7D0,preview-bg:-1,preview-border:#2E2930,preview-scrollbar:#2E2930,prompt:#B898DD,pointer:#FF7DA3,marker:#BDA9D4,spinner:#EFD472,info:#7F737D,header:#7F737D,query:#BBBBBB,disabled:#7F737D,label:#7F737D'
export THEME_MOOR_HINT='ESC[38;2;127;115;125m'
export THEME_RGB_TEXT_MUTED='127 115 125'
export THEME_RGB_ACCENT_TERTIARY='189 169 212'
export THEME_RGB_ACCENT_AMBER='239 212 114'
export THEME_RGB_ACCENT_PRIMARY='255 125 163'
