# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#727272,fg+:#ffffff,bg:-1,bg+:-1,hl:#afd787,hl+:#ffaf00:bold,gutter:-1,border:#151515,separator:#151515,scrollbar:#151515,preview-fg:#ffffff,preview-bg:-1,preview-border:#151515,preview-scrollbar:#151515,prompt:#c95c5c,pointer:#ffaf00,marker:#afd787,spinner:#556779,info:#727272,header:#727272,query:#b39066,disabled:#727272,label:#727272'
export THEME_MOOR_HINT='ESC[38;2;114;114;114m'
export THEME_RGB_TEXT_MUTED='114 114 114'
export THEME_RGB_ACCENT_TERTIARY='175 215 135'
export THEME_RGB_ACCENT_AMBER='85 103 121'
export THEME_RGB_ACCENT_PRIMARY='255 175 0'
