# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90191C25"
export THEME_BAR_TEXT="0xFFF0ECFE"
export THEME_BAR_TEXT_INACTIVE="0x80F0ECFE"
export THEME_BORDER_ACTIVE="0xB3F0ECFE"
export THEME_BORDER_INACTIVE="0xFF272935"
