# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#8a93ab,fg+:#e7ecf4,bg:-1,bg+:-1,hl:#d06f79,hl+:#d9b263:bold,gutter:-1,border:#353a45,separator:#353a45,scrollbar:#353a45,preview-fg:#e7ecf4,preview-bg:-1,preview-border:#353a45,preview-scrollbar:#353a45,prompt:#b46950,pointer:#d9b263,marker:#d06f79,spinner:#f0d399,info:#8a93ab,header:#8a93ab,query:#ebcb8b,disabled:#8a93ab,label:#8a93ab'
export THEME_MOOR_HINT='ESC[38;2;138;147;171m'
export THEME_RGB_TEXT_MUTED='138 147 171'
export THEME_RGB_ACCENT_TERTIARY='208 111 121'
export THEME_RGB_ACCENT_AMBER='240 211 153'
export THEME_RGB_ACCENT_PRIMARY='217 178 99'
