# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#949494,fg+:#ffffff,bg:-1,bg+:-1,hl:#458ee6,hl+:#ff5733:bold,gutter:-1,border:#701516,separator:#701516,scrollbar:#701516,preview-fg:#ffffff,preview-bg:-1,preview-border:#701516,preview-scrollbar:#701516,prompt:#14ba19,pointer:#ff5733,marker:#458ee6,spinner:#8ebeec,info:#949494,header:#949494,query:#ff7676,disabled:#949494,label:#949494'
export THEME_MOOR_HINT='ESC[38;2;148;148;148m'
export THEME_RGB_TEXT_MUTED='148 148 148'
export THEME_RGB_ACCENT_TERTIARY='69 142 230'
export THEME_RGB_ACCENT_AMBER='142 190 236'
export THEME_RGB_ACCENT_PRIMARY='255 87 51'
