# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#474747,fg+:#ffffff,bg:-1,bg+:-1,hl:#458ee6,hl+:#ff5733:bold,gutter:-1,border:#701516,separator:#701516,scrollbar:#701516,preview-fg:#ffffff,preview-bg:-1,preview-border:#701516,preview-scrollbar:#701516,prompt:#14ba19,pointer:#ff5733,marker:#458ee6,spinner:#701516,info:#474747,header:#474747,query:#ff7676,disabled:#474747,label:#474747'
export THEME_MOOR_HINT='ESC[38;2;71;71;71m'
export THEME_RGB_TEXT_MUTED='71 71 71'
export THEME_RGB_ACCENT_TERTIARY='69 142 230'
export THEME_RGB_ACCENT_AMBER='112 21 22'
export THEME_RGB_ACCENT_PRIMARY='255 87 51'
