# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#bdb7b2,fg+:#ffeaea,bg:-1,bg+:-1,hl:#b0a582,hl+:#9e6057:bold,gutter:-1,border:#9e6057,separator:#9e6057,scrollbar:#9e6057,preview-fg:#ffeaea,preview-bg:-1,preview-border:#9e6057,preview-scrollbar:#9e6057,prompt:#ab836c,pointer:#9e6057,marker:#b0a582,spinner:#b0a582,info:#bdb7b2,header:#bdb7b2,query:#ffeaea,disabled:#bdb7b2,label:#bdb7b2'
export THEME_MOOR_HINT='ESC[38;2;189;183;178m'
export THEME_RGB_TEXT_MUTED='189 183 178'
export THEME_RGB_ACCENT_TERTIARY='176 165 130'
export THEME_RGB_ACCENT_AMBER='176 165 130'
export THEME_RGB_ACCENT_PRIMARY='158 96 87'
