# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#8a7f76,fg+:#ffeaea,bg:-1,bg+:-1,hl:#b0a582,hl+:#9e6057:bold,gutter:-1,border:#9e6057,separator:#9e6057,scrollbar:#9e6057,preview-fg:#ffeaea,preview-bg:-1,preview-border:#9e6057,preview-scrollbar:#9e6057,prompt:#ab836c,pointer:#9e6057,marker:#b0a582,spinner:#b0a582,info:#8a7f76,header:#8a7f76,query:#ffeaea,disabled:#8a7f76,label:#8a7f76'
export THEME_MOOR_HINT='ESC[38;2;138;127;118m'
export THEME_RGB_TEXT_MUTED='138 127 118'
export THEME_RGB_ACCENT_TERTIARY='176 165 130'
export THEME_RGB_ACCENT_AMBER='176 165 130'
export THEME_RGB_ACCENT_PRIMARY='158 96 87'
