# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90151515"
export THEME_BAR_TEXT="0xFFEEEEFF"
export THEME_BAR_TEXT_INACTIVE="0x80EEEEFF"
export THEME_BORDER_ACTIVE="0xB3EEEEFF"
export THEME_BORDER_INACTIVE="0xFF777D77"
