# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90292522"
export THEME_BAR_TEXT="0xFFECE1D7"
export THEME_BAR_TEXT_INACTIVE="0x80ECE1D7"
export THEME_BORDER_ACTIVE="0xB3ECE1D7"
export THEME_BORDER_INACTIVE="0xFF253333"
