# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#817569,fg+:#f9f5ec,bg:-1,bg+:-1,hl:#d8a16c,hl+:#d9a45a:bold,gutter:-1,border:#38100a,separator:#38100a,scrollbar:#38100a,preview-fg:#f9f5ec,preview-bg:-1,preview-border:#38100a,preview-scrollbar:#38100a,prompt:#cc4d4d,pointer:#d9a45a,marker:#d8a16c,spinner:#c88a77,info:#817569,header:#817569,query:#e8c88c,disabled:#817569,label:#817569'
export THEME_MOOR_HINT='ESC[38;2;129;117;105m'
export THEME_RGB_TEXT_MUTED='129 117 105'
export THEME_RGB_ACCENT_TERTIARY='216 161 108'
export THEME_RGB_ACCENT_AMBER='200 138 119'
export THEME_RGB_ACCENT_PRIMARY='217 164 90'
