# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90161821"
export THEME_BAR_TEXT="0xFFEAF2F1"
export THEME_BAR_TEXT_INACTIVE="0x80EAF2F1"
export THEME_BORDER_ACTIVE="0xB3EAF2F1"
export THEME_BORDER_INACTIVE="0xFF282A3A"
