# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x901B1D26"
export THEME_BAR_TEXT="0xFFD7D7D7"
export THEME_BAR_TEXT_INACTIVE="0x80D7D7D7"
export THEME_BORDER_ACTIVE="0xB3D7D7D7"
export THEME_BORDER_INACTIVE="0xFF21252D"
