# Generated by `theme build`. Sourced by sketchybarrc.full/.performance.
export THEME_BAR_BG="0x90161B1E"
export THEME_BAR_TEXT="0xFFF2FFFC"
export THEME_BAR_TEXT_INACTIVE="0x80F2FFFC"
export THEME_BORDER_ACTIVE="0xB3F2FFFC"
export THEME_BORDER_INACTIVE="0xFF273136"
