# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#727272,fg+:#ffffff,bg:-1,bg+:-1,hl:#d74545,hl+:#ffaf00:bold,gutter:-1,border:#151515,separator:#151515,scrollbar:#151515,preview-fg:#ffffff,preview-bg:-1,preview-border:#151515,preview-scrollbar:#151515,prompt:#0000df,pointer:#ffaf00,marker:#d74545,spinner:#902020,info:#727272,header:#727272,query:#e6a75a,disabled:#727272,label:#727272'
export THEME_MOOR_HINT='ESC[38;2;114;114;114m'
export THEME_RGB_TEXT_MUTED='114 114 114'
export THEME_RGB_ACCENT_TERTIARY='215 69 69'
export THEME_RGB_ACCENT_AMBER='144 32 32'
export THEME_RGB_ACCENT_PRIMARY='255 175 0'
