# Generated by `theme build`. Sourced by zshrc and Claude statusline; do not edit.
export FZF_DEFAULT_OPTS='--pointer=▌ --color=fg:#7aa2a9,fg+:#cecece,bg:-1,bg+:-1,hl:#c33c33,hl+:#ec8013:bold,gutter:-1,border:#30464a,separator:#30464a,scrollbar:#30464a,preview-fg:#cecece,preview-bg:-1,preview-border:#30464a,preview-scrollbar:#30464a,prompt:#d2322d,pointer:#ec8013,marker:#c33c33,spinner:#8ebeec,info:#7aa2a9,header:#7aa2a9,query:#cd974b,disabled:#7aa2a9,label:#7aa2a9'
export THEME_MOOR_HINT='ESC[38;2;122;162;169m'
export THEME_RGB_TEXT_MUTED='122 162 169'
export THEME_RGB_ACCENT_TERTIARY='195 60 51'
export THEME_RGB_ACCENT_AMBER='142 190 236'
export THEME_RGB_ACCENT_PRIMARY='236 128 19'
